version: '3'
services:
  app:
    container_name: mutify
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    env_file:
      - .env
    secrets:
      - user_ssh_key
  mongo:
    container_name: mongo-docker
    image: mongo
    ports:
      - '27017:27017'
secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa
