version: '3'
services:
  app:
    container_name: mutify
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    env_file:
      - .env
    secrets:
      - ssh_key
    volumes:
      - src:/code
  mongo:
    container_name: mongo-docker
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/mongodb
secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
volumes:
  src: null
  db_data: null
